name: Upload Rock Cloner v2.0 ZIP (Windows)

on:
  push:
    branches:
      - windows

jobs:
  upload:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create or update v2.0 release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v2.0
          name: "Rock Cloner V2.0"
          body: |
            🪨 Rock Cloner V2.0 Windows build
            Automatically uploaded from the `windows` branch.
          draft: false
          prerelease: false
          files: |
            rockclonerv2.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
