name: Build and Release EXE

on:
  push:
    tags:
      - 'v*'   # runs when you push a tag like v1.0

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Nuitka and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka pyqt6

      - name: Build EXE with Nuitka
        run: |
          python -m nuitka ^
            --standalone ^
            --windows-console-mode=disable ^
            --enable-plugin=pyqt6 ^
            --include-qt-plugins=sensible,multimedia ^
            --include-data-dir=core=core ^
            --include-data-dir=ui=ui ^
            --include-data-dir=utils=utils ^
            --include-data-file=ROCK_CLONER.png=ROCK_CLONER.png ^
            --include-data-file=logo.png=logo.png ^
            --windows-icon-from-ico=logo.ico ^
            --output-dir=rock-cloner ^
            main.py

      - name: Zip EXE output
        run: Compress-Archive -Path rock-cloner\main.dist\* -DestinationPath ROCK_CLONER.zip

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: ROCK_CLONER.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
