name: Build and Release ROCK CLONER EXE v2.0

on:
  workflow_dispatch:
  push:
    tags:
      - 'v2.0'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Nuitka and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka pyqt6

      - name: Build ROCK CLONER EXE
        run: |
          python -m nuitka ^
            --standalone ^
            --windows-console-mode=disable ^
            --enable-plugin=pyqt6 ^
            --include-qt-plugins=sensible,multimedia ^
            --include-data-dir=core=core ^
            --include-data-dir=ui=ui ^
            --include-data-dir=utils=utils ^
            --include-data-file=ROCK_CLONER.png=ROCK_CLONER.png ^
            --include-data-file=logo.png=logo.png ^
            --windows-icon-from-ico=logo.ico ^
            --output-dir=rock-cloner ^
            main.py

      - name: Zip the built files
        run: Compress-Archive -Path rock-cloner\main.dist\* -DestinationPath ROCK_CLONER.zip

      - name: Create GitHub Release and upload ROCK CLONER EXE v2.0
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v2.0
          name: "ROCK CLONER EXE v2.0"
          body: |
            🚀 ROCK CLONER EXE v2.0  
            Automatically built with Nuitka and PyQt6.  
            Includes all assets and ready-to-run executable.
          files: ROCK_CLONER.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
